services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: forge-registry.iut-larochelle.fr/mariadb/mariadb-10.10.2
    environment:
      MYSQL_DATABASE: ${POSTGRES_DB:-app}
      MYSQL_ROOT_PASSWORD: ${POSTGRES_PASSWORD:-appdb}
      MYSQL_USER: ${POSTGRES_USER:-app}
      MYSQL_PASSWORD: ${POSTGRES_PASSWORD:-appdb}
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###